# commit to be tagged for the new release
commit = "HEAD"

project_name = "state-etcd"
github_repo = "cosi-project/state-etcd"
match_deps = "^github.com/(cosi-project/[a-zA-Z0-9-]+)$"

# previous = -
# pre_release = true

# [notes]
